BookStoreSystem/Controllers/BookController.cs
using BookStoreSystem.Data;
using BookStoreSystem.Models;
using BookStoreSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        
      
            IBookService BService;
            public BookController(IBookService _BService)
            {
                BService = _BService;
            }
            public IActionResult Index()
            {
                vmbook vm = new vmbook();

            vm.liBook = BService.LoadBook();
            vm.liAuthors = BService.LoadAuther();
                vm.liCategory = BService.LoadCategory();
                return View("index", vm);
            }
            public IActionResult Save(Book book)
            {
                string name = Guid.NewGuid().ToString() + "." + book.Image.FileName.Split('.')[1];
                string P = Path.Combine(Directory.GetCurrentDirectory(), "Images", name);
                book.Image.CopyTo(new FileStream(P, FileMode.Create));
                book.ImagePath = "http://localhost/BookStoreSystem/staticPath/" + name;
                BService.insert(book);
                vmbook vm = new vmbook();
                vm.liAuthors = BService.LoadAuther();
                vm.liCategory = BService.LoadCategory();
                vm.liBook = BService.LoadBook();

                return View("index", vm);
            }
            public IActionResult delete(int id)
            {

                BService.delete(id);
                vmbook vm = new vmbook();
                vm.liAuthors = BService.LoadAuther();
                vm.liCategory = BService.LoadCategory();
                vm.liBook = BService.LoadBook();
                return View("index", vm);
            }
            public IActionResult edit(int id)
            {
                Book b = new Book();
                b= BService.edit(id);
            
                return Json(b);
            }
            public IActionResult update(Book book)
            {
                BService.update(book);
                vmbook vm = new vmbook();
                vm.liAuthors = BService.LoadAuther();
                vm.liCategory = BService.LoadCategory();
                vm.liBook = BService.LoadBook();
                return View("index", vm);
            }
        }
}

BookStoreSystem/Controllers/CategoryController.cs
using BookStoreSystem.Data;
using BookStoreSystem.Models;
using BookStoreSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreSystem.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
       
            ICategoryService categoryService;
            public CategoryController(ICategoryService _categoryService)
            {
                categoryService = _categoryService;
            }
            public IActionResult Index()
            {


                ViewData["index"] = true;
                vmCategory vm = new vmCategory();
                vm.licategory = categoryService.loadAll();
                return View("category", vm);
            }
            public IActionResult save(vmCategory vm)
            {
                categoryService.insert(vm.category);

                ViewData["index"] = true;
                vm.licategory = categoryService.loadAll();
                return View("category", vm);
            }
            public IActionResult delete(int id)
            {

                ViewData["index"] = true;
                categoryService.delete(id);
                vmCategory vm = new vmCategory();
                vm.licategory = categoryService.loadAll();
                return View("category", vm);
            }
            public IActionResult edit(int id)
            {
                Category ctgr = new Category();
                ctgr = categoryService.edit(id);
                return Json(ctgr);

            }
            public IActionResult Update(vmCategory vm)
            {
                categoryService.update(vm.category);
                ViewData["index"] = true;
                vm.licategory = categoryService.loadAll();
                return View("category", vm);
            }
        }
}

BookStoreSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStoreSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStoreSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BookStoreSystem/Views/Shared/layoutPage.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Application> signinmanager
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/JavaScript.js"></script>
    @RenderSection("Head", false)
</head>
<body>
    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand active" href="#">Book Store</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @if (signinmanager.IsSignedIn(User))
                    {
                        <li><a asp-action="Index" asp-controller="Category">Category</a></li>
                        <li><a asp-action="Index" asp-controller="Auther">Authors</a></li>
                        <li><a asp-action="Index" asp-controller="Nationality">Nationality</a></li>
                        <li><a asp-action="Index" asp-controller="Book">Books</a></li>
                        <li><a asp-controller="Account" asp-action="NewRole">Add Role</a></li>
                        <li><a asp-controller="Account" asp-action="LogOut">Logout <span class="glyphicon glyphicon-log-out" style="margin-left:5px"></span></a></li>

                    }
                    else
                    {

                        <li><a asp-controller="Account" asp-action="index">Sign Up <span class="glyphicon glyphicon-user" style="margin-left:5px"></span></a></li>


                        <li><a asp-controller="Account" asp-action="login">Login <span class="glyphicon glyphicon-log-in" style="margin-left:5px"></span></a></li>

                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="main">
        @RenderBody()
    </div>



</body>
</html>